[2024-05-12T02:18:25.452+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-12T02:18:25.473+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tutorial_v5.third_task scheduled__2024-05-11T00:00:00+00:00 [queued]>
[2024-05-12T02:18:25.477+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tutorial_v5.third_task scheduled__2024-05-11T00:00:00+00:00 [queued]>
[2024-05-12T02:18:25.478+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-12T02:18:25.486+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): third_task> on 2024-05-11 00:00:00+00:00
[2024-05-12T02:18:25.492+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tutorial_v5', 'third_task', 'scheduled__2024-05-11T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp17vy9qhk']
[2024-05-12T02:18:25.495+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask third_task
[2024-05-12T02:18:25.494+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1277) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-12T02:18:25.495+0000] {standard_task_runner.py:63} INFO - Started process 1279 to run task
[2024-05-12T02:18:25.529+0000] {task_command.py:426} INFO - Running <TaskInstance: tutorial_v5.third_task scheduled__2024-05-11T00:00:00+00:00 [running]> on host e768b7f5ee51
[2024-05-12T02:18:25.576+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='tony arianto' AIRFLOW_CTX_DAG_ID='tutorial_v5' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-11T00:00:00+00:00'
[2024-05-12T02:18:25.576+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-12T02:18:25.585+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-12T02:18:25.585+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Hai...ini task2 akan dijalankan setelah task1!']
[2024-05-12T02:18:25.589+0000] {subprocess.py:86} INFO - Output:
[2024-05-12T02:18:25.590+0000] {subprocess.py:93} INFO - Hai...ini task2 akan dijalankan setelah task1!
[2024-05-12T02:18:25.590+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-12T02:18:25.591+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-12T02:18:25.605+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=tutorial_v5, task_id=third_task, run_id=scheduled__2024-05-11T00:00:00+00:00, execution_date=20240511T000000, start_date=20240512T021825, end_date=20240512T021825
[2024-05-12T02:18:25.636+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-12T02:18:25.645+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-12T02:18:25.646+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
