[2024-05-12T07:07:40.571+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-12T07:07:40.605+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v03.get_name scheduled__2023-07-19T00:00:00+00:00 [queued]>
[2024-05-12T07:07:40.621+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v03.get_name scheduled__2023-07-19T00:00:00+00:00 [queued]>
[2024-05-12T07:07:40.623+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-12T07:07:40.649+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_name> on 2023-07-19 00:00:00+00:00
[2024-05-12T07:07:40.654+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=9166) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-12T07:07:40.656+0000] {standard_task_runner.py:63} INFO - Started process 9176 to run task
[2024-05-12T07:07:40.658+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v03', 'get_name', 'scheduled__2023-07-19T00:00:00+00:00', '--job-id', '280', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmp7g72a8p0']
[2024-05-12T07:07:40.660+0000] {standard_task_runner.py:91} INFO - Job 280: Subtask get_name
[2024-05-12T07:07:40.731+0000] {task_command.py:426} INFO - Running <TaskInstance: our_dag_with_python_operator_v03.get_name scheduled__2023-07-19T00:00:00+00:00 [running]> on host e768b7f5ee51
[2024-05-12T07:07:40.836+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='TonyA' AIRFLOW_CTX_DAG_ID='our_dag_with_python_operator_v03' AIRFLOW_CTX_TASK_ID='get_name' AIRFLOW_CTX_EXECUTION_DATE='2023-07-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-19T00:00:00+00:00'
[2024-05-12T07:07:40.837+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-12T07:07:40.838+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-12T07:07:40.839+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: greet() missing 1 required positional argument: 'age'
[2024-05-12T07:07:40.848+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=our_dag_with_python_operator_v03, task_id=get_name, run_id=scheduled__2023-07-19T00:00:00+00:00, execution_date=20230719T000000, start_date=20240512T070740, end_date=20240512T070740
[2024-05-12T07:07:40.858+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 280 for task get_name (greet() missing 1 required positional argument: 'age'; 9176)
[2024-05-12T07:07:40.884+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-12T07:07:40.893+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-12T07:07:40.894+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
